apiVersion: v1
kind: Service
metadata:
  name: docker-k8-assignment
spec:
  type: NodePort
  selector:
    app: demoApp
  ports:
    - port: 8085
      targetPort: 8081
      nodePort: 30002